Phpeasteregg
OWASP/Nettacker pull request #277
Opened 2020-05-23 19:54 UTC by aman566

#### Checklist
- [X] I have followed the [Contributor Guidelines](https://github.com/zdresearch/OWASP-Nettacker/wiki/Developers#contribution-guidelines).
- [X] I have added the relevant documentation.
- [X] My branch is up-to-date with the Upstream master branch.

#### Changes proposed in this pull request
- [X] Added the php easter egg module in order to detect some phpinfo() pages or the php version from the gif image displayed
#### Your development environment
- OS: `Linux`
- OS Version: `Ubuntu 18.04`
- Python Version: `3.6.9`

2021-04-04 15:06 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +            'php_easter_eggs_vuln_scan', target))
@aman566  should be '_egg' not '_eggs' - please stay consistent and pay attention to details

2021-04-04 15:06 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +            data = json.dumps({'HOST': target, 'USERNAME': '', 'PASSWORD': '', 'PORT': '', 'TYPE': 'php_easter_eggs_vuln_scan',
@aman566 please use the same name you started with 'php_easter_egg_vuln_scan' (not 'eggs')

2021-04-04 15:06 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +                    messages(language, "trying_message").format(trying, total_req, num, total, target, port, 'php_easter_eggs_vuln_scan'))
@aman566 please use the same name you started with 'php_easter_egg_vuln_scan' (not 'eggs')

2021-04-04 15:06 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +            t = threading.Thread(target=__php_easter_eggs_vuln,
@aman566 please use the same name you started with 'php_easter_egg_vuln_scan' (not 'eggs')

2021-04-04 15:06 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +            ports = extra_requirements["php_easter_eggs_vuln_ports"]
@aman566 please use the same name you started with 'php_easter_egg_vuln_scan' (not 'eggs')

2021-04-04 15:06 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +    if php_easter_eggs_vuln(target, port, timeout_sec, log_in_file, language, time_sleep,
@aman566 please use the same name you started with 'php_easter_egg_vuln_scan' (not 'eggs')

2021-04-04 15:06 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +def __php_easter_eggs_vuln(target, port, timeout_sec, log_in_file, language, time_sleep,
@aman566 please use the same name you started with 'php_easter_egg_vuln_scan' (not 'eggs')

2021-04-04 15:06 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +def php_easter_eggs_vuln(target, port, timeout_sec, log_in_file, language, time_sleep,
@aman566 please use the same name you started with 'php_easter_egg_vuln_scan' (not 'eggs')

2021-04-05 20:42 UTC, securestep9 requested changes

2021-04-05 20:42 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +                req_php_credits = requests.get(req_php_credits_url, timeout=10, headers=user_agent)
@aman566 please do not hardcode the timeout - it should be timeout_sec also verify=False is missing

2021-04-05 20:42 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +                req_php_logo = requests.get(req_php_logo_url, timeout=10, headers=user_agent)
@aman566 please do not hardcode the timeout - it should be timeout_sec also verify=False is missing

2021-04-05 20:42 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +                req_zend = requests.get(req_zend_url, timeout=10, headers=user_agent)
@aman566 please do not hardcode the timeout - it should be timeout_sec also verify=False is missing

2021-04-05 20:42 UTC, securestep9 commented on lib/vuln/php_easter_egg/engine.py
> +                req_php_logo2 = requests.get(req_php_logo2_url, timeout=10, headers=user_agent)
@aman566 please do not hardcode the timeout - it should be timeout_sec also verify=False is missing

2021-09-09 20:36 UTC, Ali-Razmjoo commented
this can't be supported anymore. modules are yaml #440

2021-09-09 20:36 UTC, closed without merging